### ISSUE TITLE
Fail to --rebuild-image du PIKAUR config change

### ISSUE THREAD

**Issue by aji-prod** [aji-prod/tomato#11]
The tomato image cannot be rebuilt with the `--rebuild-image` flag due to an out of date pikaur.conf.
A new `[network]` section was introduced upstream.

``` 
---> Running in 4f9fb7c14c8f
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 41, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 518, in main
    with wrapper():
         ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 107, in __enter__
    logger.debug(
  File "/usr/lib/python3.12/site-packages/pikaur/logging_extras.py", line 81, in debug
    msg = f"{color_line(self.module_name, self.color)}: {' ' * indent}{str_message}"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pikaprint.py", line 189, in color_line
    if not color_enabled() and not force:
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/pikaprint.py", line 91, in color_enabled
    args = parse_args()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 818, in parse_args
    parsed_args, _help = _parse_args(args=args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 777, in _parse_args
    parser, help_msgs = get_parser_for_action(app=app_name, args=args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 745, in get_parser_for_action
    ("store_true", get_pikaur_bool_opts(action=pikaur_action), True, None),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/args.py", line 150, in get_pikaur_bool_opts
    "k", "keepbuild", PikaurConfig().build.KeepBuildDir.get_bool(),
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/config.py", line 781, in __getattr__
    return PikaurConfigSection(self.get_config()[attr])
                               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pikaur/config.py", line 676, in get_config
    cls.migrate_config()
  File "/usr/lib/python3.12/site-packages/pikaur/config.py", line 769, in migrate_config
    cls._migrate_deprecated_config_value(option_schema, section_name, option_name)
  File "/usr/lib/python3.12/site-packages/pikaur/config.py", line 747, in _migrate_deprecated_config_value
    current_value = cls._config[section_name][option_name]
                    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'network'
```

**Comment by aji-prod** [comment]
Fixed v0.8.4.

But we let this one open will #12 is still opened.
